name: Publish

on:

  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure the full history is fetched for tagging

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          export PATH="$HOME/.bun/bin:$PATH"

      - name: Install dependencies
        run: |
          export PATH="$HOME/.bun/bin:$PATH"
          bun install -y

      # - name: Run tests
      #   run: |
      #     export PATH="$HOME/.bun/bin:$PATH"
      #     bun run test

      - name: Run Build
        run: |
          export PATH="$HOME/.bun/bin:$PATH"
          bun run build

      - name: Bump version, commit, tag, and publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          CUSTOM_GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}  # Personal Access Token (PAT) secret
        run: |
          export PATH="$HOME/.bun/bin:$PATH"

          # Configure Git to use PAT for authentication
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"


          # Get the latest commit message
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)

          # Bump version, commit, and tag only if it's a merged PR
          if [[ "$COMMIT_MESSAGE" == Merge* ]]; then
            git remote set-url origin https://$CUSTOM_GITHUB_TOKEN@github.com/${{ github.repository }}
            # Bump version
            NEW_VERSION=$(npm version patch -m "Upgrade to %s [skip ci]")
            git push

            # Extract the version number
            VERSION=${NEW_VERSION#*v}

            git add package.json
            git commit -m "Bump version to $VERSION"
            git tag v$VERSION

            # Push the changes and tag
            git push origin master --tags
          fi
        shell: /usr/bin/bash -e {0}
